server:
  port: 9090
    
#jwt:
  #secret: Y29tLnByb2plY3QubGV0dGVyT2ZIZWFydC5qd3QudGVzdC50b2tlbg== 
  # com.project.letterOfHeart.jwt.test.token

# \uB85C\uCEEC DB

#spring:
#  datasource:
#    url: jdbc:oracle:thin:@44.209.203.85:1521:xe
#    username: springjpa
#    password: springjpa
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#  config:
#    import: application.properties
    
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: springjpa
    password: springjpa
    driver-class-name: oracle.jdbc.driver.OracleDriver
 # config:
   # import: application.properties

  #jpa:
  #  hibernate:
  #    ddl-auto: none
  #  properties:
  #    hibernate:
  #      show_sql: true
  #      format_sql: true

#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
 
 
# \uC6D0\uACA9 DB

#spring:
#  datasource:
#    url: jdbc:oracle:thin:@lohp_high?TNS_ADMIN=C:\\Wallet_lohp
#    url: jdbc:oracle:thin:@lohp_high?TNS_ADMIN=/Users/dohyeonpark/Wallet_lohp
#    url: jdbc:oracle:thin:@lohp_high?TNS_ADMIN=/Users/vanessa/importantKeyPair/Wallet_lohp
#    username: admin
#    password: HappyNewYear2023
#    driver-class-name: oracle.jdbc.driver.OracleDriver


#spring:
#  datasource:
#    url: jdbc:oracle:thin:@lohp_high?TNS_ADMIN=./src/main/resources/oracleCloud/Wallet_lohp
#    username: admin
#    password: HappyNewYear2023
#    driver-class-name: oracle.jdbc.driver.OracleDriver

# aws \uC778\uC2A4\uD134\uC2A4\uB791 \uC5F0\uACB0   
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@lohp_high?TNS_ADMIN=/home/ec2-user/Wallet_lohp
#    username: admin
#    password: HappyNewYear2023
#    driver-class-name: oracle.jdbc.driver.OracleDriver


    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#      
#      
logging.level:
  org.hibernate.SQL: debug 
  org.hibernate.type: trace
 